### ISSUE TITLE
Broken with Hashie >= 3.0.0

### ISSUE THREAD

**Issue by KOBA789** [cookpad/garage#26]
Hashie >= 3.0.0 Mash::respond_to? always returns true when given method name ending with "!", "?", "_", "=".
Ref: https://github.com/intridea/hashie/commit/5ac85162db784e4104e0cb701b4241dd1da1754b#diff-167a475bc5a73269819928a9da362073R190

It breaks this garage's code:
https://github.com/cookpad/garage/blob/master/lib/garage/representer.rb#L159

Garage assumes instance of `Hashie::Mash` to be a instance including `Garage::Representer`.
As a result of it, it fails at [here](https://github.com/cookpad/garage/blob/master/lib/garage/hypermedia_responder.rb#L35) with a message "NoMethodError: undefined method `params' for Hashie::Mash:Class ".

I suggest specifying Hashie < 3.0.0 in gemspec.

**Comment by taiki45** [comment]
I think specifying Hashie < 3.0.0 has bad side, that garage gem restricts users to use Hashie 3.0.0 above.

The one of alternatives is not checking the `value` responds to `represent!` but checking the `value` includes `Garage::Representer`. Because the `value` must respond to `params=` and `partial=` and more, checking againt `represent!` is not enought.

I think alternative plan is reasonable. How do you think?

**Comment by luvtechno** [comment]
We are facing this issue in our garage app. 

> The one of alternatives is not checking the value responds to represent! but checking the value includes Garage::Representer. Because the value must respond to params= and partial= and more, checking againt represent! is not enought.

This sounds good to me -- we are monkey patching as such and going to test with our app.
